/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistema_biblioteca;

import Controllers.LibroController;
import Controllers.TransaccionController;
import Controllers.UsuarioController;
import Model.Libro;
import Model.Transaccion;
import Model.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author santi
 */
public class Registrar_Tramites extends javax.swing.JInternalFrame {
         private DefaultComboBoxModel CbAlu = new DefaultComboBoxModel();
         private DefaultComboBoxModel CbLibros = new DefaultComboBoxModel();
         private LibroController LiController = new LibroController();
         private UsuarioController UsController = new UsuarioController();
         private TransaccionController TraController = new TransaccionController();
       
    /**
     * Creates new form Registrar_Tramites
     */
    public Registrar_Tramites() {
        initComponents();
        CargarAlumnos();
        CargarLibros();
    }
    
    public void CargarAlumnos(){
        List<Usuario> lst = UsController.GetLstAllAlumnosController();
        for(Usuario item:lst){
            this.CboxAlu.addItem(item.getNombre());
        }
    }
    
    public void CargarLibros(){
        List<Libro> lst = LiController.GetNomLibrosController();
        for(Libro istem:lst){
            this.CboxLibros.addItem(istem.getTitulo());
        }
    }
    
    public String GetSelectedAlu(){
        return  CboxAlu.getSelectedItem().toString();
    }
    
    public String GetSelectedLibro(){
        return CboxLibros.getSelectedItem().toString();
    }
    
    public void TranGetCorrelativo(){
        txtCodigoT.setText(TraController.GetCorrelativoTController()+"");
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CboxLibros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CboxAlu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoT = new javax.swing.JTextField();
        txtNumCopias = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFPrestamo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFAPoxDevolucion = new javax.swing.JTextField();
        btn_Registar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Reservar = new javax.swing.JButton();
        txt_FReserva = new javax.swing.JTextField();
        txt_FRecojo = new javax.swing.JTextField();
        Btn_New = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tramite");

        jLabel1.setText("Libros:");

        CboxLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona......." }));
        CboxLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxLibrosActionPerformed(evt);
            }
        });

        jLabel2.setText("Alumnos:");

        CboxAlu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona............" }));
        CboxAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxAluActionPerformed(evt);
            }
        });

        jLabel3.setText("Num_Copias:");

        jLabel4.setText("Codigo_Transaccion:");

        txtCodigoT.setEditable(false);

        txtNumCopias.setEditable(false);

        jLabel5.setText("Fecha_Prestamo:");

        jLabel6.setText("Fecha_AproxDevolucion:");

        txtFAPoxDevolucion.setEditable(false);

        btn_Registar.setText("Registrar");
        btn_Registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setText("Frecha_Reserva:");

        jLabel8.setText("Frecha_Recojo:");

        btn_Reservar.setText("Reservar");

        txt_FReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FReservaActionPerformed(evt);
            }
        });

        Btn_New.setText("Nuevo");
        Btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(Btn_New))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CboxAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CboxLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(btn_Registar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(txtFAPoxDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(btn_Cancelar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(txtNumCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Reservar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_FReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(txt_FRecojo))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_New))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CboxAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CboxLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFAPoxDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Registar)
                                    .addComponent(btn_Cancelar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_FReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_FRecojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(btn_Reservar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboxAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxAluActionPerformed

    private void btn_RegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistarActionPerformed
        // TODO add your handling code here:
        Libro objLi = LiController.GetLibrosXnombres(GetSelectedLibro());
        int objUs = UsController.GetUsuarioXId(GetSelectedAlu());
        Transaccion objTran = new Transaccion();
        objTran.setCodigo(Integer.parseInt(this.txtCodigoT.getText()));
        objTran.setId_Usuario(objUs);
        objTran.setId_Libro(objLi.getCodigo());
        objTran.setNum_Copias_Libro(1);
        objTran.setFecha_Prestamo(this.txtFPrestamo.getText());
        objTran.setFecha_Devolucion(this.txtFAPoxDevolucion.getText());   
        objTran.setFecha_Reserva("");
        objTran.setEstado("");
        objTran.setId_Estados(2);
    
        TraController.AgregarTransaccionPrestamo(objTran);
    }//GEN-LAST:event_btn_RegistarActionPerformed

    private void txt_FReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FReservaActionPerformed

    private void CboxLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxLibrosActionPerformed
        // TODO add your handling code here:
      List<Libro> lst = LiController.GetNumLibrosController(GetSelectedLibro());
      LocalDate fecha = LocalDate.now();
      for(Libro x:lst){
          this.txtNumCopias.setText(x.getNumCopias()+"");
          this.txtFPrestamo.setText(fecha+"");
          this.txtFAPoxDevolucion.setText(fecha.plusDays(14)+"");
          this.txt_FReserva.setText(fecha+ "");
          this.txt_FRecojo.setText(fecha.plusDays(5)+"");
          
      }
    }//GEN-LAST:event_CboxLibrosActionPerformed

    private void Btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NewActionPerformed
        // TODO add your handling code here:
         TranGetCorrelativo();
         txtNumCopias.setText("");
         txtFPrestamo.setText("");
         txtFAPoxDevolucion.setText("");
         txt_FReserva.setText("");
         txt_FReserva.setText("");
    }//GEN-LAST:event_Btn_NewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_New;
    private javax.swing.JComboBox<String> CboxAlu;
    private javax.swing.JComboBox<String> CboxLibros;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Registar;
    private javax.swing.JButton btn_Reservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCodigoT;
    private javax.swing.JTextField txtFAPoxDevolucion;
    private javax.swing.JTextField txtFPrestamo;
    private javax.swing.JTextField txtNumCopias;
    private javax.swing.JTextField txt_FRecojo;
    private javax.swing.JTextField txt_FReserva;
    // End of variables declaration//GEN-END:variables
}
